/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DlqRouteImport } from './routes/dlq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhooksIndexRouteImport } from './routes/webhooks/index'
import { Route as WebhooksNewRouteImport } from './routes/webhooks/new'
import { Route as WebhooksIdRouteImport } from './routes/webhooks/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DlqRoute = DlqRouteImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksIndexRoute = WebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksNewRoute = WebhooksNewRouteImport.update({
  id: '/webhooks/new',
  path: '/webhooks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksIdRoute = WebhooksIdRouteImport.update({
  id: '/webhooks/$id',
  path: '/webhooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dlq': typeof DlqRoute
  '/settings': typeof SettingsRoute
  '/webhooks/$id': typeof WebhooksIdRoute
  '/webhooks/new': typeof WebhooksNewRoute
  '/webhooks': typeof WebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dlq': typeof DlqRoute
  '/settings': typeof SettingsRoute
  '/webhooks/$id': typeof WebhooksIdRoute
  '/webhooks/new': typeof WebhooksNewRoute
  '/webhooks': typeof WebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dlq': typeof DlqRoute
  '/settings': typeof SettingsRoute
  '/webhooks/$id': typeof WebhooksIdRoute
  '/webhooks/new': typeof WebhooksNewRoute
  '/webhooks/': typeof WebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dlq'
    | '/settings'
    | '/webhooks/$id'
    | '/webhooks/new'
    | '/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dlq'
    | '/settings'
    | '/webhooks/$id'
    | '/webhooks/new'
    | '/webhooks'
  id:
    | '__root__'
    | '/'
    | '/dlq'
    | '/settings'
    | '/webhooks/$id'
    | '/webhooks/new'
    | '/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DlqRoute: typeof DlqRoute
  SettingsRoute: typeof SettingsRoute
  WebhooksIdRoute: typeof WebhooksIdRoute
  WebhooksNewRoute: typeof WebhooksNewRoute
  WebhooksIndexRoute: typeof WebhooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dlq': {
      id: '/dlq'
      path: '/dlq'
      fullPath: '/dlq'
      preLoaderRoute: typeof DlqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/': {
      id: '/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/new': {
      id: '/webhooks/new'
      path: '/webhooks/new'
      fullPath: '/webhooks/new'
      preLoaderRoute: typeof WebhooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/$id': {
      id: '/webhooks/$id'
      path: '/webhooks/$id'
      fullPath: '/webhooks/$id'
      preLoaderRoute: typeof WebhooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DlqRoute: DlqRoute,
  SettingsRoute: SettingsRoute,
  WebhooksIdRoute: WebhooksIdRoute,
  WebhooksNewRoute: WebhooksNewRoute,
  WebhooksIndexRoute: WebhooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
