// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apikeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (key_hash, key_prefix, environment, name, rate_limit_per_second)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, key_prefix, environment, name, rate_limit_per_second, created_at
`

type CreateAPIKeyParams struct {
	KeyHash            string      `json:"key_hash"`
	KeyPrefix          string      `json:"key_prefix"`
	Environment        string      `json:"environment"`
	Name               pgtype.Text `json:"name"`
	RateLimitPerSecond pgtype.Int4 `json:"rate_limit_per_second"`
}

type CreateAPIKeyRow struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyPrefix          string             `json:"key_prefix"`
	Environment        string             `json:"environment"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Environment,
		arg.Name,
		arg.RateLimitPerSecond,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.KeyPrefix,
		&i.Environment,
		&i.Name,
		&i.RateLimitPerSecond,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, key_prefix, environment, name, rate_limit_per_second, revoked_at, created_at
FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyPrefix          string             `json:"key_prefix"`
	Environment        string             `json:"environment"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.KeyPrefix,
		&i.Environment,
		&i.Name,
		&i.RateLimitPerSecond,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, key_prefix, environment, name, rate_limit_per_second, created_at, last_used_at, revoked_at
FROM api_keys
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyPrefix          string             `json:"key_prefix"`
	Environment        string             `json:"environment"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyPrefix,
			&i.Environment,
			&i.Name,
			&i.RateLimitPerSecond,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
