// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apikeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (key_hash, key_prefix, name, rate_limit_per_second, org_id, project_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, key_prefix, name, rate_limit_per_second, created_at, org_id, project_id
`

type CreateAPIKeyParams struct {
	KeyHash            string      `json:"key_hash"`
	KeyPrefix          string      `json:"key_prefix"`
	Name               pgtype.Text `json:"name"`
	RateLimitPerSecond pgtype.Int4 `json:"rate_limit_per_second"`
	OrgID              pgtype.Text `json:"org_id"`
	ProjectID          string      `json:"project_id"`
}

type CreateAPIKeyRow struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyPrefix          string             `json:"key_prefix"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OrgID              pgtype.Text        `json:"org_id"`
	ProjectID          string             `json:"project_id"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Name,
		arg.RateLimitPerSecond,
		arg.OrgID,
		arg.ProjectID,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.KeyPrefix,
		&i.Name,
		&i.RateLimitPerSecond,
		&i.CreatedAt,
		&i.OrgID,
		&i.ProjectID,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, key_prefix, name, rate_limit_per_second, revoked_at, created_at, org_id, project_id
FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyPrefix          string             `json:"key_prefix"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OrgID              pgtype.Text        `json:"org_id"`
	ProjectID          string             `json:"project_id"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.KeyPrefix,
		&i.Name,
		&i.RateLimitPerSecond,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.OrgID,
		&i.ProjectID,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, key_prefix, name, rate_limit_per_second, revoked_at, created_at, org_id, project_id
FROM api_keys
WHERE id = $1
`

type GetAPIKeyByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyPrefix          string             `json:"key_prefix"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OrgID              pgtype.Text        `json:"org_id"`
	ProjectID          string             `json:"project_id"`
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (GetAPIKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i GetAPIKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.KeyPrefix,
		&i.Name,
		&i.RateLimitPerSecond,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.OrgID,
		&i.ProjectID,
	)
	return i, err
}

const getAPIKeyByIdAndOrg = `-- name: GetAPIKeyByIdAndOrg :one
SELECT id, key_prefix, name, rate_limit_per_second, revoked_at, created_at, org_id, project_id
FROM api_keys
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
`

type GetAPIKeyByIdAndOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.Text `json:"org_id"`
}

type GetAPIKeyByIdAndOrgRow struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyPrefix          string             `json:"key_prefix"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OrgID              pgtype.Text        `json:"org_id"`
	ProjectID          string             `json:"project_id"`
}

func (q *Queries) GetAPIKeyByIdAndOrg(ctx context.Context, arg GetAPIKeyByIdAndOrgParams) (GetAPIKeyByIdAndOrgRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByIdAndOrg, arg.ID, arg.OrgID)
	var i GetAPIKeyByIdAndOrgRow
	err := row.Scan(
		&i.ID,
		&i.KeyPrefix,
		&i.Name,
		&i.RateLimitPerSecond,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.OrgID,
		&i.ProjectID,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, key_prefix, name, rate_limit_per_second, created_at, last_used_at, revoked_at, org_id, project_id
FROM api_keys
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyPrefix          string             `json:"key_prefix"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	OrgID              pgtype.Text        `json:"org_id"`
	ProjectID          string             `json:"project_id"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyPrefix,
			&i.Name,
			&i.RateLimitPerSecond,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.OrgID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByOrg = `-- name: ListAPIKeysByOrg :many

SELECT id, key_prefix, name, rate_limit_per_second, created_at, last_used_at, revoked_at, project_id
FROM api_keys
WHERE org_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByOrgRow struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyPrefix          string             `json:"key_prefix"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	ProjectID          string             `json:"project_id"`
}

// Organization-scoped queries for dashboard
func (q *Queries) ListAPIKeysByOrg(ctx context.Context, orgID pgtype.Text) ([]ListAPIKeysByOrgRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByOrgRow{}
	for rows.Next() {
		var i ListAPIKeysByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyPrefix,
			&i.Name,
			&i.RateLimitPerSecond,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByProject = `-- name: ListAPIKeysByProject :many
SELECT id, key_prefix, name, rate_limit_per_second, created_at, last_used_at, revoked_at, project_id
FROM api_keys
WHERE org_id = $1 AND project_id = $2
ORDER BY created_at DESC
`

type ListAPIKeysByProjectParams struct {
	OrgID     pgtype.Text `json:"org_id"`
	ProjectID string      `json:"project_id"`
}

type ListAPIKeysByProjectRow struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyPrefix          string             `json:"key_prefix"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	ProjectID          string             `json:"project_id"`
}

func (q *Queries) ListAPIKeysByProject(ctx context.Context, arg ListAPIKeysByProjectParams) ([]ListAPIKeysByProjectRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByProject, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByProjectRow{}
	for rows.Next() {
		var i ListAPIKeysByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyPrefix,
			&i.Name,
			&i.RateLimitPerSecond,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const revokeAPIKeyByOrg = `-- name: RevokeAPIKeyByOrg :exec
UPDATE api_keys SET revoked_at = NOW()
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyByOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.Text `json:"org_id"`
}

func (q *Queries) RevokeAPIKeyByOrg(ctx context.Context, arg RevokeAPIKeyByOrgParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKeyByOrg, arg.ID, arg.OrgID)
	return err
}

const revokeAPIKeyByProject = `-- name: RevokeAPIKeyByProject :exec
UPDATE api_keys SET revoked_at = NOW()
WHERE id = $1 AND org_id = $2 AND project_id = $3 AND revoked_at IS NULL
`

type RevokeAPIKeyByProjectParams struct {
	ID        pgtype.UUID `json:"id"`
	OrgID     pgtype.Text `json:"org_id"`
	ProjectID string      `json:"project_id"`
}

func (q *Queries) RevokeAPIKeyByProject(ctx context.Context, arg RevokeAPIKeyByProjectParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKeyByProject, arg.ID, arg.OrgID, arg.ProjectID)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
