// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor, action, org_id, target, detail, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	Actor     string      `json:"actor"`
	Action    string      `json:"action"`
	OrgID     pgtype.Text `json:"org_id"`
	Target    pgtype.Text `json:"target"`
	Detail    []byte      `json:"detail"`
	IpAddress *netip.Addr `json:"ip_address"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Actor,
		arg.Action,
		arg.OrgID,
		arg.Target,
		arg.Detail,
		arg.IpAddress,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, timestamp, actor, action, org_id, target, detail, ip_address
FROM audit_log
WHERE
    ($1::VARCHAR IS NULL OR org_id = $1)
    AND ($2::TEXT IS NULL OR action = $2)
    AND ($3::TIMESTAMPTZ IS NULL OR timestamp >= $3)
ORDER BY id DESC
LIMIT $4
`

type ListAuditLogsParams struct {
	OrgID  pgtype.Text        `json:"org_id"`
	Action pgtype.Text        `json:"action"`
	Since  pgtype.Timestamptz `json:"since"`
	Limit  int32              `json:"limit"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.OrgID,
		arg.Action,
		arg.Since,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Actor,
			&i.Action,
			&i.OrgID,
			&i.Target,
			&i.Detail,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
