// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deliveries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDeliveriesByStatus = `-- name: CountDeliveriesByStatus :many
SELECT status, COUNT(*) as count
FROM event_deliveries
WHERE created_at > NOW() - INTERVAL '24 hours'
GROUP BY status
`

type CountDeliveriesByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountDeliveriesByStatus(ctx context.Context) ([]CountDeliveriesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countDeliveriesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDeliveriesByStatusRow{}
	for rows.Next() {
		var i CountDeliveriesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEventDelivery = `-- name: CreateEventDelivery :one
INSERT INTO event_deliveries (event_id, receiver_type, receiver_id, consumer_name, client_id, status, attempt, delivered_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, event_id, receiver_type, receiver_id, consumer_name, client_id, status, attempt, created_at, delivered_at, acked_at, error
`

type CreateEventDeliveryParams struct {
	EventID      string             `json:"event_id"`
	ReceiverType string             `json:"receiver_type"`
	ReceiverID   pgtype.UUID        `json:"receiver_id"`
	ConsumerName pgtype.Text        `json:"consumer_name"`
	ClientID     pgtype.Text        `json:"client_id"`
	Status       string             `json:"status"`
	Attempt      int32              `json:"attempt"`
	DeliveredAt  pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) CreateEventDelivery(ctx context.Context, arg CreateEventDeliveryParams) (EventDelivery, error) {
	row := q.db.QueryRow(ctx, createEventDelivery,
		arg.EventID,
		arg.ReceiverType,
		arg.ReceiverID,
		arg.ConsumerName,
		arg.ClientID,
		arg.Status,
		arg.Attempt,
		arg.DeliveredAt,
	)
	var i EventDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ReceiverType,
		&i.ReceiverID,
		&i.ConsumerName,
		&i.ClientID,
		&i.Status,
		&i.Attempt,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.AckedAt,
		&i.Error,
	)
	return i, err
}

const getDeliveriesByConsumer = `-- name: GetDeliveriesByConsumer :many
SELECT id, event_id, receiver_type, receiver_id, consumer_name, client_id, status, attempt, created_at, delivered_at, acked_at, error FROM event_deliveries
WHERE consumer_name = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetDeliveriesByConsumerParams struct {
	ConsumerName pgtype.Text `json:"consumer_name"`
	Limit        int32       `json:"limit"`
}

func (q *Queries) GetDeliveriesByConsumer(ctx context.Context, arg GetDeliveriesByConsumerParams) ([]EventDelivery, error) {
	rows, err := q.db.Query(ctx, getDeliveriesByConsumer, arg.ConsumerName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventDelivery{}
	for rows.Next() {
		var i EventDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ReceiverType,
			&i.ReceiverID,
			&i.ConsumerName,
			&i.ClientID,
			&i.Status,
			&i.Attempt,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.AckedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveriesByWebhook = `-- name: GetDeliveriesByWebhook :many
SELECT id, event_id, receiver_type, receiver_id, consumer_name, client_id, status, attempt, created_at, delivered_at, acked_at, error FROM event_deliveries
WHERE receiver_type = 'webhook' AND receiver_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetDeliveriesByWebhookParams struct {
	ReceiverID pgtype.UUID `json:"receiver_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) GetDeliveriesByWebhook(ctx context.Context, arg GetDeliveriesByWebhookParams) ([]EventDelivery, error) {
	rows, err := q.db.Query(ctx, getDeliveriesByWebhook, arg.ReceiverID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventDelivery{}
	for rows.Next() {
		var i EventDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ReceiverType,
			&i.ReceiverID,
			&i.ConsumerName,
			&i.ClientID,
			&i.Status,
			&i.Attempt,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.AckedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventDeliveries = `-- name: GetEventDeliveries :many
SELECT id, event_id, receiver_type, receiver_id, consumer_name, client_id, status, attempt, created_at, delivered_at, acked_at, error FROM event_deliveries
WHERE event_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetEventDeliveries(ctx context.Context, eventID string) ([]EventDelivery, error) {
	rows, err := q.db.Query(ctx, getEventDeliveries, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventDelivery{}
	for rows.Next() {
		var i EventDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ReceiverType,
			&i.ReceiverID,
			&i.ConsumerName,
			&i.ClientID,
			&i.Status,
			&i.Attempt,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.AckedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventDeliveriesWithWebhookURL = `-- name: GetEventDeliveriesWithWebhookURL :many
SELECT ed.id, ed.event_id, ed.receiver_type, ed.receiver_id, ed.consumer_name, ed.client_id, ed.status, ed.attempt, ed.created_at, ed.delivered_at, ed.acked_at, ed.error, w.url as webhook_url
FROM event_deliveries ed
LEFT JOIN webhooks w ON ed.receiver_type = 'webhook' AND ed.receiver_id = w.id
WHERE ed.event_id = $1
ORDER BY ed.created_at DESC
`

type GetEventDeliveriesWithWebhookURLRow struct {
	ID           pgtype.UUID        `json:"id"`
	EventID      string             `json:"event_id"`
	ReceiverType string             `json:"receiver_type"`
	ReceiverID   pgtype.UUID        `json:"receiver_id"`
	ConsumerName pgtype.Text        `json:"consumer_name"`
	ClientID     pgtype.Text        `json:"client_id"`
	Status       string             `json:"status"`
	Attempt      int32              `json:"attempt"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeliveredAt  pgtype.Timestamptz `json:"delivered_at"`
	AckedAt      pgtype.Timestamptz `json:"acked_at"`
	Error        pgtype.Text        `json:"error"`
	WebhookUrl   pgtype.Text        `json:"webhook_url"`
}

func (q *Queries) GetEventDeliveriesWithWebhookURL(ctx context.Context, eventID string) ([]GetEventDeliveriesWithWebhookURLRow, error) {
	rows, err := q.db.Query(ctx, getEventDeliveriesWithWebhookURL, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventDeliveriesWithWebhookURLRow{}
	for rows.Next() {
		var i GetEventDeliveriesWithWebhookURLRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ReceiverType,
			&i.ReceiverID,
			&i.ConsumerName,
			&i.ClientID,
			&i.Status,
			&i.Attempt,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.AckedAt,
			&i.Error,
			&i.WebhookUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventDeliveryAcked = `-- name: UpdateEventDeliveryAcked :exec
UPDATE event_deliveries
SET status = 'acked', acked_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateEventDeliveryAcked(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateEventDeliveryAcked, id)
	return err
}

const updateEventDeliveryDLQ = `-- name: UpdateEventDeliveryDLQ :exec
UPDATE event_deliveries
SET status = 'dlq', error = $2
WHERE id = $1
`

type UpdateEventDeliveryDLQParams struct {
	ID    pgtype.UUID `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) UpdateEventDeliveryDLQ(ctx context.Context, arg UpdateEventDeliveryDLQParams) error {
	_, err := q.db.Exec(ctx, updateEventDeliveryDLQ, arg.ID, arg.Error)
	return err
}

const updateEventDeliveryNacked = `-- name: UpdateEventDeliveryNacked :exec
UPDATE event_deliveries
SET status = 'nacked', error = $2
WHERE id = $1
`

type UpdateEventDeliveryNackedParams struct {
	ID    pgtype.UUID `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) UpdateEventDeliveryNacked(ctx context.Context, arg UpdateEventDeliveryNackedParams) error {
	_, err := q.db.Exec(ctx, updateEventDeliveryNacked, arg.ID, arg.Error)
	return err
}

const updateEventDeliveryStatus = `-- name: UpdateEventDeliveryStatus :exec
UPDATE event_deliveries
SET status = $2, acked_at = $3, error = $4
WHERE id = $1
`

type UpdateEventDeliveryStatusParams struct {
	ID      pgtype.UUID        `json:"id"`
	Status  string             `json:"status"`
	AckedAt pgtype.Timestamptz `json:"acked_at"`
	Error   pgtype.Text        `json:"error"`
}

func (q *Queries) UpdateEventDeliveryStatus(ctx context.Context, arg UpdateEventDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateEventDeliveryStatus,
		arg.ID,
		arg.Status,
		arg.AckedAt,
		arg.Error,
	)
	return err
}
