// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByAPIKey = `-- name: CountEventsByAPIKey :one
SELECT COUNT(*) FROM events WHERE api_key_id = $1
`

func (q *Queries) CountEventsByAPIKey(ctx context.Context, apiKeyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByAPIKey, apiKeyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByOrg = `-- name: CountEventsByOrg :one
SELECT COUNT(*) FROM events WHERE org_id = $1
`

func (q *Queries) CountEventsByOrg(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByProject = `-- name: CountEventsByProject :one
SELECT COUNT(*) FROM events WHERE org_id = $1 AND project_id = $2
`

type CountEventsByProjectParams struct {
	OrgID     string      `json:"org_id"`
	ProjectID pgtype.Text `json:"project_id"`
}

func (q *Queries) CountEventsByProject(ctx context.Context, arg CountEventsByProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByProject, arg.OrgID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, topic, api_key_id, org_id, project_id, payload_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateEventParams struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	OrgID       string             `json:"org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.ID,
		arg.Topic,
		arg.ApiKeyID,
		arg.OrgID,
		arg.ProjectID,
		arg.PayloadSize,
		arg.CreatedAt,
	)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, topic, api_key_id, org_id, project_id, payload_size, created_at
FROM events
WHERE id = $1
`

type GetEventRow struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	OrgID       string             `json:"org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEvent(ctx context.Context, id string) (GetEventRow, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.ApiKeyID,
		&i.OrgID,
		&i.ProjectID,
		&i.PayloadSize,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByIDAndOrg = `-- name: GetEventByIDAndOrg :one
SELECT id, topic, api_key_id, org_id, project_id, payload_size, created_at
FROM events
WHERE id = $1 AND org_id = $2
`

type GetEventByIDAndOrgParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetEventByIDAndOrgRow struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	OrgID       string             `json:"org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEventByIDAndOrg(ctx context.Context, arg GetEventByIDAndOrgParams) (GetEventByIDAndOrgRow, error) {
	row := q.db.QueryRow(ctx, getEventByIDAndOrg, arg.ID, arg.OrgID)
	var i GetEventByIDAndOrgRow
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.ApiKeyID,
		&i.OrgID,
		&i.ProjectID,
		&i.PayloadSize,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByIDAndProject = `-- name: GetEventByIDAndProject :one
SELECT id, topic, api_key_id, org_id, project_id, payload_size, created_at
FROM events
WHERE id = $1 AND org_id = $2 AND project_id = $3
`

type GetEventByIDAndProjectParams struct {
	ID        string      `json:"id"`
	OrgID     string      `json:"org_id"`
	ProjectID pgtype.Text `json:"project_id"`
}

type GetEventByIDAndProjectRow struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	OrgID       string             `json:"org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEventByIDAndProject(ctx context.Context, arg GetEventByIDAndProjectParams) (GetEventByIDAndProjectRow, error) {
	row := q.db.QueryRow(ctx, getEventByIDAndProject, arg.ID, arg.OrgID, arg.ProjectID)
	var i GetEventByIDAndProjectRow
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.ApiKeyID,
		&i.OrgID,
		&i.ProjectID,
		&i.PayloadSize,
		&i.CreatedAt,
	)
	return i, err
}

const getEventStats = `-- name: GetEventStats :one
SELECT
    COUNT(*) as total,
    COUNT(CASE WHEN created_at > NOW() - INTERVAL '24 hours' THEN 1 END) as last_24h,
    COUNT(CASE WHEN created_at > NOW() - INTERVAL '1 hour' THEN 1 END) as last_hour
FROM events
WHERE org_id = $1
`

type GetEventStatsRow struct {
	Total    int64 `json:"total"`
	Last24h  int64 `json:"last_24h"`
	LastHour int64 `json:"last_hour"`
}

func (q *Queries) GetEventStats(ctx context.Context, orgID string) (GetEventStatsRow, error) {
	row := q.db.QueryRow(ctx, getEventStats, orgID)
	var i GetEventStatsRow
	err := row.Scan(&i.Total, &i.Last24h, &i.LastHour)
	return i, err
}

const getEventStatsByProject = `-- name: GetEventStatsByProject :one
SELECT
    COUNT(*) as total,
    COUNT(CASE WHEN created_at > NOW() - INTERVAL '24 hours' THEN 1 END) as last_24h,
    COUNT(CASE WHEN created_at > NOW() - INTERVAL '1 hour' THEN 1 END) as last_hour
FROM events
WHERE org_id = $1 AND project_id = $2
`

type GetEventStatsByProjectParams struct {
	OrgID     string      `json:"org_id"`
	ProjectID pgtype.Text `json:"project_id"`
}

type GetEventStatsByProjectRow struct {
	Total    int64 `json:"total"`
	Last24h  int64 `json:"last_24h"`
	LastHour int64 `json:"last_hour"`
}

func (q *Queries) GetEventStatsByProject(ctx context.Context, arg GetEventStatsByProjectParams) (GetEventStatsByProjectRow, error) {
	row := q.db.QueryRow(ctx, getEventStatsByProject, arg.OrgID, arg.ProjectID)
	var i GetEventStatsByProjectRow
	err := row.Scan(&i.Total, &i.Last24h, &i.LastHour)
	return i, err
}

const listEventsByOrg = `-- name: ListEventsByOrg :many
SELECT id, topic, api_key_id, org_id, project_id, payload_size, created_at
FROM events
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListEventsByOrgParams struct {
	OrgID string `json:"org_id"`
	Limit int32  `json:"limit"`
}

type ListEventsByOrgRow struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	OrgID       string             `json:"org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListEventsByOrg(ctx context.Context, arg ListEventsByOrgParams) ([]ListEventsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listEventsByOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsByOrgRow{}
	for rows.Next() {
		var i ListEventsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.ApiKeyID,
			&i.OrgID,
			&i.ProjectID,
			&i.PayloadSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByOrgAndTopic = `-- name: ListEventsByOrgAndTopic :many
SELECT id, topic, api_key_id, org_id, project_id, payload_size, created_at
FROM events
WHERE org_id = $1 AND topic LIKE $2
ORDER BY created_at DESC
LIMIT $3
`

type ListEventsByOrgAndTopicParams struct {
	OrgID string `json:"org_id"`
	Topic string `json:"topic"`
	Limit int32  `json:"limit"`
}

type ListEventsByOrgAndTopicRow struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	OrgID       string             `json:"org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListEventsByOrgAndTopic(ctx context.Context, arg ListEventsByOrgAndTopicParams) ([]ListEventsByOrgAndTopicRow, error) {
	rows, err := q.db.Query(ctx, listEventsByOrgAndTopic, arg.OrgID, arg.Topic, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsByOrgAndTopicRow{}
	for rows.Next() {
		var i ListEventsByOrgAndTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.ApiKeyID,
			&i.OrgID,
			&i.ProjectID,
			&i.PayloadSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByProject = `-- name: ListEventsByProject :many
SELECT id, topic, api_key_id, org_id, project_id, payload_size, created_at
FROM events
WHERE org_id = $1 AND project_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListEventsByProjectParams struct {
	OrgID     string      `json:"org_id"`
	ProjectID pgtype.Text `json:"project_id"`
	Limit     int32       `json:"limit"`
}

type ListEventsByProjectRow struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	OrgID       string             `json:"org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListEventsByProject(ctx context.Context, arg ListEventsByProjectParams) ([]ListEventsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listEventsByProject, arg.OrgID, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsByProjectRow{}
	for rows.Next() {
		var i ListEventsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.ApiKeyID,
			&i.OrgID,
			&i.ProjectID,
			&i.PayloadSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByProjectAndTopic = `-- name: ListEventsByProjectAndTopic :many
SELECT id, topic, api_key_id, org_id, project_id, payload_size, created_at
FROM events
WHERE org_id = $1 AND project_id = $2 AND topic LIKE $3
ORDER BY created_at DESC
LIMIT $4
`

type ListEventsByProjectAndTopicParams struct {
	OrgID     string      `json:"org_id"`
	ProjectID pgtype.Text `json:"project_id"`
	Topic     string      `json:"topic"`
	Limit     int32       `json:"limit"`
}

type ListEventsByProjectAndTopicRow struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	OrgID       string             `json:"org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListEventsByProjectAndTopic(ctx context.Context, arg ListEventsByProjectAndTopicParams) ([]ListEventsByProjectAndTopicRow, error) {
	rows, err := q.db.Query(ctx, listEventsByProjectAndTopic,
		arg.OrgID,
		arg.ProjectID,
		arg.Topic,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsByProjectAndTopicRow{}
	for rows.Next() {
		var i ListEventsByProjectAndTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.ApiKeyID,
			&i.OrgID,
			&i.ProjectID,
			&i.PayloadSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTopicAndOrg = `-- name: ListEventsByTopicAndOrg :many
SELECT id, topic, api_key_id, org_id, project_id, payload_size, created_at
FROM events
WHERE topic LIKE $1 AND org_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListEventsByTopicAndOrgParams struct {
	Topic string `json:"topic"`
	OrgID string `json:"org_id"`
	Limit int32  `json:"limit"`
}

type ListEventsByTopicAndOrgRow struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	OrgID       string             `json:"org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListEventsByTopicAndOrg(ctx context.Context, arg ListEventsByTopicAndOrgParams) ([]ListEventsByTopicAndOrgRow, error) {
	rows, err := q.db.Query(ctx, listEventsByTopicAndOrg, arg.Topic, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsByTopicAndOrgRow{}
	for rows.Next() {
		var i ListEventsByTopicAndOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.ApiKeyID,
			&i.OrgID,
			&i.ProjectID,
			&i.PayloadSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
