// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByAPIKey = `-- name: CountEventsByAPIKey :one
SELECT COUNT(*) FROM events WHERE api_key_id = $1
`

func (q *Queries) CountEventsByAPIKey(ctx context.Context, apiKeyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByAPIKey, apiKeyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, topic, api_key_id, environment, payload_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateEventParams struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	Environment string             `json:"environment"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.ID,
		arg.Topic,
		arg.ApiKeyID,
		arg.Environment,
		arg.PayloadSize,
		arg.CreatedAt,
	)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, topic, api_key_id, environment, payload_size, created_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.ApiKeyID,
		&i.Environment,
		&i.PayloadSize,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsByTopic = `-- name: ListEventsByTopic :many
SELECT id, topic, api_key_id, environment, payload_size, created_at
FROM events
WHERE topic LIKE $1
ORDER BY created_at DESC
LIMIT $2
`

type ListEventsByTopicParams struct {
	Topic string `json:"topic"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListEventsByTopic(ctx context.Context, arg ListEventsByTopicParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByTopic, arg.Topic, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.ApiKeyID,
			&i.Environment,
			&i.PayloadSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
