// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyHash            string             `json:"key_hash"`
	KeyPrefix          string             `json:"key_prefix"`
	Environment        string             `json:"environment"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
}

type ConsumerGroup struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	Environment string             `json:"environment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	Environment string             `json:"environment"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
