// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID                 pgtype.UUID        `json:"id"`
	KeyHash            string             `json:"key_hash"`
	KeyPrefix          string             `json:"key_prefix"`
	Environment        string             `json:"environment"`
	Name               pgtype.Text        `json:"name"`
	RateLimitPerSecond pgtype.Int4        `json:"rate_limit_per_second"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	OrgID              pgtype.Text        `json:"org_id"`
}

type ConsumerGroup struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	Environment string             `json:"environment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID          string             `json:"id"`
	Topic       string             `json:"topic"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	Environment string             `json:"environment"`
	PayloadSize int32              `json:"payload_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Webhook struct {
	ID          pgtype.UUID        `json:"id"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	Url         string             `json:"url"`
	Topics      []string           `json:"topics"`
	Secret      string             `json:"secret"`
	Enabled     bool               `json:"enabled"`
	Environment string             `json:"environment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WebhookDelivery struct {
	ID             pgtype.UUID        `json:"id"`
	WebhookID      pgtype.UUID        `json:"webhook_id"`
	EventID        string             `json:"event_id"`
	Topic          string             `json:"topic"`
	Status         string             `json:"status"`
	Attempt        int32              `json:"attempt"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   pgtype.Text        `json:"response_body"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
}
