// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orgs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (id, name, external_id, nats_public_key, nats_account_seed, billing_tier)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, external_id, nats_public_key, nats_account_seed, billing_tier, created_at, updated_at
`

type CreateOrgParams struct {
	ID              string      `json:"id"`
	Name            string      `json:"name"`
	ExternalID      pgtype.Text `json:"external_id"`
	NatsPublicKey   string      `json:"nats_public_key"`
	NatsAccountSeed pgtype.Text `json:"nats_account_seed"`
	BillingTier     pgtype.Text `json:"billing_tier"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg,
		arg.ID,
		arg.Name,
		arg.ExternalID,
		arg.NatsPublicKey,
		arg.NatsAccountSeed,
		arg.BillingTier,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalID,
		&i.NatsPublicKey,
		&i.NatsAccountSeed,
		&i.BillingTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, external_id, nats_public_key, nats_account_seed, billing_tier, created_at, updated_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalID,
		&i.NatsPublicKey,
		&i.NatsAccountSeed,
		&i.BillingTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgByExternalID = `-- name: GetOrgByExternalID :one
SELECT id, name, external_id, nats_public_key, nats_account_seed, billing_tier, created_at, updated_at FROM orgs WHERE external_id = $1
`

func (q *Queries) GetOrgByExternalID(ctx context.Context, externalID pgtype.Text) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByExternalID, externalID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalID,
		&i.NatsPublicKey,
		&i.NatsAccountSeed,
		&i.BillingTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrgs = `-- name: ListOrgs :many
SELECT id, name, external_id, nats_public_key, nats_account_seed, billing_tier, created_at, updated_at FROM orgs ORDER BY created_at ASC
`

func (q *Queries) ListOrgs(ctx context.Context) ([]Org, error) {
	rows, err := q.db.Query(ctx, listOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Org{}
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExternalID,
			&i.NatsPublicKey,
			&i.NatsAccountSeed,
			&i.BillingTier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgBillingTier = `-- name: UpdateOrgBillingTier :one
UPDATE orgs SET billing_tier = $2, updated_at = now() WHERE id = $1 RETURNING id, name, external_id, nats_public_key, nats_account_seed, billing_tier, created_at, updated_at
`

type UpdateOrgBillingTierParams struct {
	ID          string      `json:"id"`
	BillingTier pgtype.Text `json:"billing_tier"`
}

func (q *Queries) UpdateOrgBillingTier(ctx context.Context, arg UpdateOrgBillingTierParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrgBillingTier, arg.ID, arg.BillingTier)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalID,
		&i.NatsPublicKey,
		&i.NatsAccountSeed,
		&i.BillingTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrgNatsPublicKey = `-- name: UpdateOrgNatsPublicKey :exec
UPDATE orgs SET nats_public_key = $2, updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateOrgNatsPublicKey(ctx context.Context, id string, natsPublicKey string) error {
	_, err := q.db.Exec(ctx, updateOrgNatsPublicKey, id, natsPublicKey)
	return err
}

const updateOrgNatsAccountSeed = `-- name: UpdateOrgNatsAccountSeed :exec
UPDATE orgs SET nats_account_seed = $2, updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateOrgNatsAccountSeed(ctx context.Context, id string, natsAccountSeed string) error {
	_, err := q.db.Exec(ctx, updateOrgNatsAccountSeed, id, natsAccountSeed)
	return err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM orgs WHERE id = $1
`

func (q *Queries) DeleteOrg(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOrg, id)
	return err
}
