// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
)

const countProjectsByOrg = `-- name: CountProjectsByOrg :one
SELECT COUNT(*) FROM projects WHERE org_id = $1
`

func (q *Queries) CountProjectsByOrg(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, org_id, name, slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, org_id, name, slug, created_at, updated_at
`

type CreateProjectParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
	Name  string `json:"name"`
	Slug  string `json:"slug"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1 AND org_id = $2
`

type DeleteProjectParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.OrgID)
	return err
}

const getOrCreateDefaultProject = `-- name: GetOrCreateDefaultProject :one
INSERT INTO projects (id, org_id, name, slug, created_at, updated_at)
VALUES ($1, $2, 'Default', 'default', NOW(), NOW())
ON CONFLICT (org_id, slug) DO UPDATE SET updated_at = NOW()
RETURNING id, org_id, name, slug, created_at, updated_at
`

type GetOrCreateDefaultProjectParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetOrCreateDefaultProject(ctx context.Context, arg GetOrCreateDefaultProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getOrCreateDefaultProject, arg.ID, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, name, slug, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByOrgAndID = `-- name: GetProjectByOrgAndID :one
SELECT id, org_id, name, slug, created_at, updated_at FROM projects WHERE id = $1 AND org_id = $2
`

type GetProjectByOrgAndIDParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetProjectByOrgAndID(ctx context.Context, arg GetProjectByOrgAndIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByOrgAndID, arg.ID, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, org_id, name, slug, created_at, updated_at FROM projects WHERE org_id = $1 AND slug = $2
`

type GetProjectBySlugParams struct {
	OrgID string `json:"org_id"`
	Slug  string `json:"slug"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.OrgID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByOrg = `-- name: ListProjectsByOrg :many
SELECT id, org_id, name, slug, created_at, updated_at FROM projects WHERE org_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListProjectsByOrg(ctx context.Context, orgID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE(NULLIF($3, ''), name),
    slug = COALESCE(NULLIF($4, ''), slug),
    updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, slug, created_at, updated_at
`

type UpdateProjectParams struct {
	ID      string      `json:"id"`
	OrgID   string      `json:"org_id"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.OrgID,
		arg.Column3,
		arg.Column4,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
