// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyStats = `-- name: GetAPIKeyStats :one

SELECT
    COUNT(*) FILTER (WHERE revoked_at IS NULL) as total,
    COUNT(*) FILTER (WHERE revoked_at IS NULL AND last_used_at > NOW() - INTERVAL '24 hours') as active_24h
FROM api_keys
WHERE org_id = $1
`

type GetAPIKeyStatsRow struct {
	Total     int64 `json:"total"`
	Active24h int64 `json:"active_24h"`
}

// Stats queries for observability dashboard
func (q *Queries) GetAPIKeyStats(ctx context.Context, orgID pgtype.Text) (GetAPIKeyStatsRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyStats, orgID)
	var i GetAPIKeyStatsRow
	err := row.Scan(&i.Total, &i.Active24h)
	return i, err
}

const getWebhookDeliveryStats = `-- name: GetWebhookDeliveryStats :one
SELECT
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE status = 'success') as success_count,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_count,
    COUNT(*) FILTER (WHERE status = 'pending') as pending_count
FROM webhook_deliveries wd
JOIN webhooks w ON w.id = wd.webhook_id
JOIN api_keys ak ON ak.id = w.api_key_id
WHERE ak.org_id = $1 AND wd.created_at > NOW() - INTERVAL '24 hours'
`

type GetWebhookDeliveryStatsRow struct {
	Total        int64 `json:"total"`
	SuccessCount int64 `json:"success_count"`
	FailedCount  int64 `json:"failed_count"`
	PendingCount int64 `json:"pending_count"`
}

func (q *Queries) GetWebhookDeliveryStats(ctx context.Context, orgID pgtype.Text) (GetWebhookDeliveryStatsRow, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryStats, orgID)
	var i GetWebhookDeliveryStatsRow
	err := row.Scan(
		&i.Total,
		&i.SuccessCount,
		&i.FailedCount,
		&i.PendingCount,
	)
	return i, err
}

const getWebhookDeliveryStatsByWebhook = `-- name: GetWebhookDeliveryStatsByWebhook :many
SELECT
    w.id as webhook_id,
    w.url,
    COUNT(*) as total_deliveries,
    COUNT(*) FILTER (WHERE wd.status = 'success') as success_count,
    AVG(EXTRACT(EPOCH FROM (wd.delivered_at - wd.created_at)) * 1000)::int as avg_latency_ms
FROM webhooks w
JOIN api_keys ak ON ak.id = w.api_key_id
LEFT JOIN webhook_deliveries wd ON w.id = wd.webhook_id AND wd.created_at > NOW() - INTERVAL '24 hours'
WHERE ak.org_id = $1 AND ak.revoked_at IS NULL
GROUP BY w.id, w.url
`

type GetWebhookDeliveryStatsByWebhookRow struct {
	WebhookID       pgtype.UUID `json:"webhook_id"`
	Url             string      `json:"url"`
	TotalDeliveries int64       `json:"total_deliveries"`
	SuccessCount    int64       `json:"success_count"`
	AvgLatencyMs    int32       `json:"avg_latency_ms"`
}

func (q *Queries) GetWebhookDeliveryStatsByWebhook(ctx context.Context, orgID pgtype.Text) ([]GetWebhookDeliveryStatsByWebhookRow, error) {
	rows, err := q.db.Query(ctx, getWebhookDeliveryStatsByWebhook, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWebhookDeliveryStatsByWebhookRow{}
	for rows.Next() {
		var i GetWebhookDeliveryStatsByWebhookRow
		if err := rows.Scan(
			&i.WebhookID,
			&i.Url,
			&i.TotalDeliveries,
			&i.SuccessCount,
			&i.AvgLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookStats = `-- name: GetWebhookStats :one
SELECT
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE enabled = true) as enabled,
    COUNT(*) FILTER (WHERE enabled = false) as disabled
FROM webhooks w
JOIN api_keys ak ON ak.id = w.api_key_id
WHERE ak.org_id = $1 AND ak.revoked_at IS NULL
`

type GetWebhookStatsRow struct {
	Total    int64 `json:"total"`
	Enabled  int64 `json:"enabled"`
	Disabled int64 `json:"disabled"`
}

func (q *Queries) GetWebhookStats(ctx context.Context, orgID pgtype.Text) (GetWebhookStatsRow, error) {
	row := q.db.QueryRow(ctx, getWebhookStats, orgID)
	var i GetWebhookStatsRow
	err := row.Scan(&i.Total, &i.Enabled, &i.Disabled)
	return i, err
}
